language: d

d:
  - dmd
  - dmd-beta
  - dmd-2.074.1
  - dmd-2.073.2
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - ldc
  - ldc-beta
  - ldc-1.1.1 # eq to dmd v2.071.2
  - gdc

sudo: false

os:
  - linux
  - osx

script:
  - dub build --build=release --config=library
  - dub test --build=unittest --config=unittest
  - dub build --build=release --config=quickstartExample

matrix:
  allow_failures:
    - d: gdc
      os: osx