language: d

d:
  - dmd
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.2
  - ldc
  - ldc-1.1.0-beta6
  - ldc-0.17.2
  - gdc

sudo: false

script:
  - dub build --build=release --config=library
  - dub test --build=unittest --config=unittest
  - dub build --build=release --config=quickstartExample
