language: d

d:
  - dmd
  - dmd-2.072.2
  - dmd-2.071.2
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.074.0-b2
  - ldc
  - ldc-1.0.0
  - ldc-0.17.2
  - ldc-1.2.0-beta2
  - gdc

sudo: false

script:
  - dub build --build=release --config=library
  - dub test --build=unittest --config=unittest
  - dub build --build=release --config=quickstartExample
